#
#
# things you probably want to change
#
#

# no trailing slash
url: https://jasxnhuynh.github.io/portfolio

# for header and meta tags
title: Jason Huynh
description: website showcasing my work

# set external to true if linking outside your website
# for internal, make sure to include preceding slash
nav-links:
  - name: Home
    url: /
    external: false
  # - name: Blog
  #   url: /blog
  #   external: false

# for the homepage image + big text next to it
greeting_image: assets/me.JPG
# 100-200 characters recommended
greeting_text: |
  <span style="font-size: 28px; display: block; margin-top: -10px; line-height: 1.0;">Hi, I'm Jason!</span>\\
  <span style="font-size: 16px; line-height: 1.2;">[LinkedIn](https://linkedin.com/in/jasxnhuynh) | [GitHub](https://github.com/jasxnhuynh) | [Email](mailto:jasonhuynh5856@gmail.com)</span>

# show blog post excerpts on blog page
show_excerpts: false
excerpt_word_count: 70

# long date: April 20, 1969
long_date: true
# short date: Apr ‘69
short_date: false

#
#
# things you probably don't want to change
#
#
defaults:
  - # applies the default layout to all files in the project
    scope:
      path: ""
    values:
      layout: "default"
  - # sets is_post=true for all blog posts
    scope:
      path: ""
      type: posts
    values:
      is_post: true
permalink: /:title # so we have /about instead of /about.html, and /blog-post instead of /2019-11-22-blog-post.html
sass:
  style: compressed # compress the CSS file generated from the SCSS styles file
